### PR TITLE
jinja-yaml - add whitespace around variable in curly braces

### PR DESCRIPTION
**Pull request by mjbear**
jinja-yaml - add whitespace around variable in curly braces based on best practices in official Jinja documentation

ex: {{vrf}} becomes {{ vrf }}

### CODE REVIEW

**Review by mthiel117 — CHANGES_REQUESTED** [review]
Needs rebased from previous PR 130

**Review by mthiel117 — CHANGES_REQUESTED** [review]
Needs rebased from previous PR 130

**Comment by mjbear** [comment]
Rebased from current position of upstream's main branch.

@mthiel117 
Will go ahead and rebase PR #132 to this current PR. ;-)

**Review by JulioPDX — APPROVED** [review]
Thank you for the contribution! Woohoo

**Review by mthiel117 — APPROVED** [review]
LGTM.  Thanks Michael

**Pull request merged**
