### PR TITLE
ansible - set lab password

### PR DESCRIPTION
**Pull request by mjbear**
ansible - warning note reminder to set lab password

### CODE REVIEW

**Review by mthiel117 — CHANGES_REQUESTED** [review]
Needs rebased from previous PR 134.

**Comment by mjbear** [comment]
Rebased from the current position of upstream's main branch.

**Review by JulioPDX — APPROVED** [review]
Great run on PRs, thanks again

**Comment by JulioPDX** [comment]
fixes #128

**Review by mthiel117 — APPROVED** [review]
LGTM.

**Pull request merged**
