### PR TITLE
Modify Original AVD Guide - Add L3LS CI AVD Guide

### PR DESCRIPTION
**Pull request by RestlessWanderer**
This PR continues multiple changes.

- Created two new directories
    - l2ls
    - l3ls
    
- Rename original AVD lab guide files and fix dead links
    - Rename from AVD to AVD L2LS
    - avd.md renamed to overview.md  ( moved under l2ls dir )
    - avd_lab_guide.md renamed to l2ls_lab_guide.md ( moved under l2ls dir ) 
   
- Added images for l3ls guide to assets/images

- Added new files for l3ls lab guide
    - New section called AVD L3LS EVPN/VXLAN
    - overview.md ( under l3ls dir )
    - l3ls_lab_guide.md ( under l3ls dir )

- Fixed all dead links as a result of guide move.

### CODE REVIEW

**Comment by mthiel117** [comment]
Need to add this section to the L2LS Lab Guide.

### Change To Lab Working Directory

Now that AVD is updated, lets move into the appropriate directory so we can access the files necessary for this L3LS Lab!

```bash
cd labs/L2LS
```

**Comment by mthiel117** [comment]
This section on L3LS_EVPN Lab guide is not rendering correct.  Tabs need removed.

```
???+ abstract "Where did those VLANs come from?" You should notice some VLANs that we didn't define anywhere in the _NETWORK_SERVICES.yml data model which aren't related to MLAG. Specifically, these will be VLAN SVIs Vlan1199 and Vlan3009.
```

**Comment by mthiel117** [comment]
newline need after line 145, before the next heading

**Comment by mthiel117** [comment]
L3LS_EVPN, under section "Build and Deploy Changes for EVPN Gateway Functionality". The code blocks for s1-bdr1 and s1-bdr2 are not rendering correctly.

**Comment by mthiel117** [comment]
same thing under this section:

Verify the EVPN overlay peerings to Site 2.

**Comment by mthiel117** [comment]
L3LS_EVPN Lab

Under Day 2 Operations....  change:

Our multi-site L2LS network

to 

Our multi-site L3LS_EVPN network

**Comment by RestlessWanderer** [comment]
> L3LS_EVPN Lab
> 
> Under Day 2 Operations.... change:
> 
> Our multi-site L2LS network
> 
> to
> 
> Our multi-site L3LS_EVPN network

This has been fixed.

**Comment by RestlessWanderer** [comment]
> newline need after line 145, before the next heading

I already have a blank line between the ``` and ### **Verification**

**Comment by RestlessWanderer** [comment]
> L3LS_EVPN, under section "Build and Deploy Changes for EVPN Gateway Functionality". The code blocks for s1-bdr1 and s1-bdr2 are not rendering correctly.

This is caused by the markdown extension - mdx_truly_sane_lists.  Proposing removing this extension.

**Comment by RestlessWanderer** [comment]
> same thing under this section:
> 
> Verify the EVPN overlay peerings to Site 2.

This is caused by the markdown extension - mdx_truly_sane_lists.  Proposing removing this extension.

**Comment by RestlessWanderer** [comment]
> This section on L3LS_EVPN Lab guide is not rendering correct. Tabs need removed.
> 
> ```
> ???+ abstract "Where did those VLANs come from?" You should notice some VLANs that we didn't define anywhere in the _NETWORK_SERVICES.yml data model which aren't related to MLAG. Specifically, these will be VLAN SVIs Vlan1199 and Vlan3009.
> ```

This is caused by the markdown extension - mdx_truly_sane_lists.  Proposing removing this extension.

**Review by mthiel117 — APPROVED** [review]
LGTM.

**Review by JulioPDX — APPROVED** [review]
LGTM

**Pull request merged**
